### ISSUE TITLE
Errors when trying to build the project

### ISSUE THREAD

**Issue by RawToast** [ttu-ttu/ebook-reader#30]
I tried building the reader to test changes, etc. and ran into a few errors when dealing with the scss files. Maybe I am doing it wrong, but I don't see a development guide:

Steps taken:

* Fresh clone
* `npm install`
* `npn run build`

Npm version: 8.1.0

```
Error: ./src/styles.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './package.json' is not defined by "exports" in /Users/jim/Github/ebook-reader/node_modules/postcss/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:416:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:669:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/jim/Github/ebook-reader/node_modules/css-loader/dist/index.js:12:39)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1147:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /Users/jim/Github/ebook-reader/node_modules/webpack/lib/NormalModule.js:316:20
    at /Users/jim/Github/ebook-reader/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/jim/Github/ebook-reader/node_modules/loader-runner/lib/LoaderRunner.js:172:11
    at loadLoader (/Users/jim/Github/ebook-reader/node_modules/loader-runner/lib/loadLoader.js:32:11)
    at iteratePitchingLoaders (/Users/jim/Github/ebook-reader/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/Users/jim/Github/ebook-reader/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
    at NormalModule.doBuild (/Users/jim/Github/ebook-reader/node_modules/webpack/lib/NormalModule.js:295:3)
    at NormalModule.build (/Users/jim/Github/ebook-reader/node_modules/webpack/lib/NormalModule.js:446:15)
    at Compilation.buildModule (/Users/jim/Github/ebook-reader/node_modules/webpack/lib/Compilation.js:739:10)
    at /Users/jim/Github/ebook-reader/node_modules/webpack/lib/Compilation.js:1111:12
    at /Users/jim/Github/ebook-reader/node_modules/webpack/lib/NormalModuleFactory.js:409:6
    at /Users/jim/Github/ebook-reader/node_modules/webpack/lib/NormalModuleFactory.js:155:13
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/Users/jim/Github/ebook-reader/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at AsyncSeriesWaterfallHook.lazyCompileHook (/Users/jim/Github/ebook-reader/node_modules/webpack/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/jim/Github/ebook-reader/node_modules/webpack/lib/NormalModuleFactory.js:138:29
    at /Users/jim/Github/ebook-reader/node_modules/webpack/lib/NormalModuleFactory.js:346:9
 @ multi ./src/styles.scss styles[0]
```

**Comment by ttu-ttu** [comment]
Just tried following the exact same steps on a `node:16-slim` and couldn't reproduce it. That being said if you're making changes to contribute, I would suggest using `npm start` instead of `npm run build`.

Also, I believe the supported node version for the current commit is version 14.

**Comment by RawToast** [comment]
Thank, using nvm with node v16 seems to have done the trick 🎉
